from ._base import document_rule, DocumentRule

from ._addglossarylinks import add_glossary_links
from ._applymacros import apply_macros
from ._createtableofcontents import create_table_of_contents
from ._movetotargetdirrelative import move_to_target_dir_relative
from ._renameuniquelyforconfluence import rename_uniquely_for_confluence, path_is_confluence_style
from ._sanitizeinternallinks import santize_internal_links

from ._rulesets import GetRulesForStyle
